import { getActivityHubData, createNewsletterCampaign, transitionNewsletter, updateNewsletterCampaign } from "../activity/actions";

export const dynamic = "force-dynamic";

export default async function NewsletterAdminPage() {
  const { campaigns } = await getActivityHubData();
  return <section className="mx-auto max-w-5xl space-y-6">
    <header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Communications</p><h1 className="mt-2 text-2xl font-semibold text-slate-900">メルマガ企画</h1><p className="mt-2 text-sm text-slate-600">配信サービスに送る前の企画・編集・学びを一元管理します。</p></header>
    <form action={createNewsletterCampaign} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-2">
      <input name="title" required placeholder="企画名（例：今週の余白）" className="rounded-xl border border-slate-200 px-3 py-2 text-sm md:col-span-2" />
      <select name="segment" className="rounded-xl border border-slate-200 px-3 py-2 text-sm"><option value="all">全員</option><option value="new">新規登録者</option><option value="active">継続利用者</option><option value="dormant">休眠ユーザー</option><option value="premium">有料会員</option></select>
      <input name="purpose" placeholder="目的（再訪・学び・啓発など）" className="rounded-xl border border-slate-200 px-3 py-2 text-sm" />
      <button className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 md:col-span-2">下書きを作成</button>
    </form>
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold text-slate-800">企画一覧</h2><div className="mt-3 divide-y divide-slate-100">{campaigns.length === 0 ? <p className="py-6 text-center text-xs text-slate-400">企画はまだありません。</p> : campaigns.map((item) => <details key={item.id} className="group py-3"><summary className="flex cursor-pointer list-none items-center justify-between gap-4"><div><p className="text-sm font-medium text-slate-800">{item.title}</p><p className="mt-1 text-xs text-slate-500">対象：{item.segment} / 目的：{item.purpose ?? "未設定"}</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-slate-50 px-2 py-1 text-[11px] text-slate-600">{item.status === "draft" ? "下書き" : item.status}</span>{item.status === "draft" && <form action={transitionNewsletter.bind(null, item.id, "planned")}><button className="text-[11px] text-indigo-700 underline">配信計画へ</button></form>}{item.status === "planned" && <form action={transitionNewsletter.bind(null, item.id, "ready")}><button className="text-[11px] text-emerald-700 underline">配信準備完了</button></form>}</div></summary><form action={updateNewsletterCampaign.bind(null, item.id)} className="mt-4 space-y-3 rounded-xl bg-slate-50 p-4"><input name="subject" defaultValue={item.subject ?? ""} placeholder="件名" className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm" /><textarea name="body" defaultValue={item.body ?? ""} placeholder="本文（配信サービスへ貼り付ける原稿）" rows={6} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm" /><div className="grid gap-2 sm:grid-cols-4">{([["openRate","開封率"],["clickRate","クリック率"],["returnRate","再訪率"],["unsubscribeRate","解除率"]] as const).map(([name,label]) => <label key={name} className="text-[11px] text-slate-500">{label}<input name={name} defaultValue={item[name] ?? ""} placeholder="%" type="number" step="0.1" className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-2 py-1.5 text-sm" /></label>)}</div><textarea name="learnings" defaultValue={item.learnings ?? ""} placeholder="配信後の学び" rows={3} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm" /><button className="rounded-lg bg-slate-800 px-3 py-2 text-xs font-medium text-white">内容と指標を保存</button></form></details>)}</div></div>
  </section>;
}
