import { getActivityHubData, createActivityReport, transitionActivityReport } from "../activity/actions";

export const dynamic = "force-dynamic";

export default async function ActivityReportsPage() {
  const { reports, snapshots } = await getActivityHubData();
  return <section className="mx-auto max-w-5xl space-y-6">
    <header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Public Activity</p><h1 className="mt-2 text-2xl font-semibold text-slate-900">活動レポート</h1><p className="mt-2 text-sm text-slate-600">匿名化された傾向とYOHAKUの活動を、月次・季節ごとの発信素材にまとめます。</p></header>
    <form action={createActivityReport} className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold text-slate-800">レポートの下書きを作成</h2><input name="title" required placeholder="レポート名（例：2026年夏のYOHAKU）" className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm" /><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-500">開始日<input type="date" name="periodStart" required className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2 text-sm" /></label><label className="text-xs text-slate-500">終了日<input type="date" name="periodEnd" required className="mt-1 block w-full rounded-xl border border-slate-200 px-3 py-2 text-sm" /></label></div><textarea name="summary" required placeholder="匿名インサイト・活動の概要" rows={5} className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm" /><p className="text-[11px] leading-5 text-amber-700">公開前に、少人数の集計や個人を特定できる表現がないか確認してください。</p><button className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-medium text-white">下書きを保存</button></form>
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold text-slate-800">レポート一覧</h2><div className="mt-3 divide-y divide-slate-100">{reports.length === 0 ? <p className="py-6 text-center text-xs text-slate-400">まだレポートはありません。</p> : reports.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm font-medium text-slate-800">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.periodStart.toLocaleDateString("ja-JP")} 〜 {item.periodEnd.toLocaleDateString("ja-JP")}</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-slate-50 px-2 py-1 text-[11px] text-slate-600">{item.status}</span>{item.status === "draft" && <form action={transitionActivityReport.bind(null, item.id, "review_required")}><button className="text-[11px] text-slate-600 underline">レビューへ</button></form>}{item.status === "review_required" && <form action={transitionActivityReport.bind(null, item.id, "published")}><button className="text-[11px] text-emerald-700 underline">公開</button></form>}</div></div>)}</div></div>
    <div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><h2 className="text-sm font-semibold text-slate-800">既存のコミュニティ集約データ</h2><p className="mt-1 text-xs text-slate-500">公開レポートへ使う前に、集計人数と匿名化状態を確認してください。</p><div className="mt-3 grid gap-3 sm:grid-cols-3">{snapshots.map((item) => <div key={item.id} className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-xs text-slate-500">{item.periodStart.toLocaleDateString("ja-JP")} 〜</p><p className="mt-1 text-lg font-semibold text-slate-900">{item.momentCount.toLocaleString()} <span className="text-xs font-normal text-slate-500">件</span></p><p className="mt-1 text-[11px] text-slate-500">{item.dominantTheme ?? "テーマ未設定"}</p></div>)}</div></div>
  </section>;
}
