import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { buildMemoryTimeline } from "@/lib/memory/timeline-builder";
import { generateWeeklyReflection } from "@/lib/memory/weekly-reflection";
import { generateMemorySnapshot } from "@/lib/memory/theme-extractor";
import { MemoryTimeline } from "@/components/memory/MemoryTimeline";
import { ThemeCluster } from "@/components/memory/ThemeCluster";
import { WeeklyReflection } from "@/components/memory/WeeklyReflection";
import { ResurfacedMemory } from "@/components/memory/ResurfacedMemory";

export const metadata = {
  title: "Memory - YOHAKU",
};

export default async function MemoryPage() {
  const session = await auth();
  if (!session?.user?.id) {
    redirect("/login");
  }

  const userId = session.user.id;

  // 1. Fetch Timeline
  const timeline = await buildMemoryTimeline(userId);

  // 2. Fetch or Generate Weekly Reflection
  // In a real app, this might be cached or generated by a Cron Job.
  // For now, we dynamically generate it if needed, or just fetch a pre-computed one.
  const weeklyReflectionText = await generateWeeklyReflection(userId);

  // 3. Fetch Long-term themes (Snapshot)
  // We'll look for an existing snapshot for the last 30 days, or generate one if missing.
  let snapshot = await prisma.memorySnapshot.findFirst({
    where: { userId },
    orderBy: { createdAt: "desc" },
  });

  if (!snapshot) {
    // Attempt to generate one
    snapshot = await generateMemorySnapshot(userId, 30);
  }

  const themes = snapshot?.themes ? (snapshot.themes as string[]) : [];

  // 4. Fetch Resurfaced Memory (if any exists from Cron or recent save)
  const recentResurfacing = await prisma.memoryResurfacing.findFirst({
    where: { userId },
    orderBy: { createdAt: "desc" },
  });

  return (
    <div className="max-w-4xl mx-auto py-12 px-6">
      <header className="mb-16">
        <h1 className="text-3xl font-serif text-notion-text dark:text-white mb-4">
          記憶の地層
        </h1>
        <p className="text-sm text-gray-500">
          過去の余白が、時間とともに静かに沈殿する空間。
        </p>
      </header>

      {/* Resurfaced Memory (Past connections) */}
      <ResurfacedMemory resurfacing={recentResurfacing} />

      {/* Weekly Reflection */}
      <WeeklyReflection reflection={weeklyReflectionText} />

      {/* Long-term Themes */}
      <ThemeCluster themes={themes} />

      {/* Timeline Grouped by Month */}
      <MemoryTimeline timeline={timeline} />
    </div>
  );
}