export const CONTENT_ITEM_SAFE_SELECT = {
  id: true,
  userId: true,
  type: true,
  title: true,
  url: true,
  thumbnailUrl: true,
  domain: true,
  fileUrl: true,
  fileName: true,
  fileSize: true,
  metadata: true,
  memoryState: true,
  summary: true,
  aiTags: true,
  contentType: true,
  reflection: true,
  embedding: true,
  embeddingModel: true,
  embeddingDimensions: true,
  aiVersion: true,
  aiProcessedAt: true,
  createdAt: true,
  updatedAt: true,
} as const;
